### PR TITLE
Added styling

### PR DESCRIPTION
**Pull request by CaddyDz**
* rearranged files for better support in github pages
* added bulma CSS framework
* format files for better readability

### CODE REVIEW

**Comment by CaddyDz** [comment]
Yo! merge means accept

You shoudl not immediately accept pull requests, but fine

**Comment by RiyadhJove** [comment]
why xd !!

**Comment by CaddyDz** [comment]
Well anyone in the world can send you pull requests, and if you merge directly, the code might not work but you trust me so it's fine

**Comment by RiyadhJove** [comment]
yeah that's why I merged it immediately

**Comment by CaddyDz** [comment]
Okay let's make this calculator live

**Comment by RiyadhJove** [comment]
go ahead

**Comment by CaddyDz** [comment]
Click settings on the top and then scroll down to GitHub pages and choose the source, it's the master branch

**Pull request merged**
